version: "3.7"
services:
  mysql:
    image: mysql
    container_name: todo_mysql
    volumes:
      - ./initial_schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_ROOT_PASSWORD=password